baseURL = "/monthly-budget-planner/"
title = "Monthly Budget Planner"
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[params]
  version = "1.2.8"

[build]
  writeStats = false
  
[minify]
  minifyOutput = true