baseURL = "/monthly-budget-planner/"
title = "Monthly Budget Planner"
disableKinds = ["taxonomy", "term", "rss", "sitemap"]

[params]
  version = "1.3.0"

[build]
  writeStats = false
  
[minify]
  minifyOutput = true